# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'First player wins'), ('S', 'Second player wins'), ('D', 'Draw')], default='A', max_length=1),
        ),
    ]
